name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - name: Run Unit Tests
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test # will run `yarn test` command
      - name: Run E2E Tests
        shell: bash
        run: |
           yarn start:mock &
           sleep 2m &&
           curl http://localhost:8000 &&
           yarn test
